#let config = (
    caf_name: "",
    faculty_name: "",
    id_study_field: "",
    study_field: "",
    work_type: "",
    work_num: "",
    discipline_name: "",
    theme: "",
    themecol2:"",
    author: (nwa:"", group:""),
    adviser: (nwa:""),
    city: "",
    date: datetime.today().display("[day].[month].[year]"),
    year: datetime.today().display("[year]"), 
)